kind: Service
apiVersion: v1
metadata:
  name: backendapi
  labels:
    app: myhellow
    service: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer