apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: cron
  namespace: default
spec:
  type: bindings.cron
  version: v1
  metadata:
  - name: schedule
    value: "@every 10s" # valid cron schedule
  - name: direction
    value: "input"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chronexampleapp
  labels:
    app: chronexample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chronexample
  template:
    metadata:
      labels:
        app: chronexample
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "chronexampleapp"
        dapr.io/app-port: "5002"
        dapr.io/enable-api-logging: "true"
        dapr.io/config: "tracing"
    spec:
      containers:
      - name: chronexample
        image: containerregistryre.azurecr.io/external-binding-sample:latest
        env:
          - name: APP_PORT
            value: "5002"
        ports:
          - containerPort: 5002
      imagePullSecrets:
      - name: acr-auth-secret
