apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderfrontendapp
  labels:
    app: orderfrontendapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderfrontendapp
  template:
    metadata:
      labels:
        app: orderfrontendapp
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "orderfrontendapp"
        dapr.io/app-port: "80"
        dapr.io/app-protocol: "http"
        dapr.io/metrics-enabled: "true"
    spec:
      containers:
      - name: orderfrontendapp
        image: reisenberg123/dapr-traffic-control-order-frontend:1.0
        ports:
        - containerPort: 80
        env:
        - name: APP_PORT
          value: "80"
        - name: DAPR_HTTP_PORT
          value: "3500"
        - name: DAPR_GRPC_PORT
          value: "50001"
        - name: APP_PROTOCOL
          value: "http"
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
      - name: daprd
        image: ghcr.io/dapr/daprd:1.15.4
        command: ["/daprd"]
        args:
        - "--app-id"
        - "orderfrontendapp"
        - "--app-port"
        - "80"
        - "--app-protocol"
        - "http"
        - "--dapr-http-port"
        - "3500"
        - "--dapr-grpc-port"
        - "50001"
        - "--metrics-port"
        - "9090"
        - "--log-level"
        - "info"
        - "--mode"
        - "kubernetes"
        - "--control-plane-address"
        - "dapr-api.dapr-system.svc.cluster.local:443"
        - "--sentry-address"
        - "dapr-sentry.dapr-system.svc.cluster.local:443"
        - "--enable-metrics"
        - "--placement-host-address"
        - "dapr-placement-server.dapr-system.svc.cluster.local:50005"
        - "--enable-mtls"
        env:
        - name: NAMESPACE
          value: "default"
        - name: DAPR_TRUST_ANCHORS
          value: |
            -----BEGIN CERTIFICATE-----
            MIIBcDCCARegAwIBAgIRAPAEhAQq2j4sPFPmfGNH5AkwCgYIKoZIzj0EAwIwGDEW
            MBQGA1UEChMNY2x1c3Rlci5sb2NhbDAeFw0yNTA0MTMwNzI3MTBaFw0yNjA0MTMw
            NzQyMTBaMBgxFjAUBgNVBAoTDWNsdXN0ZXIubG9jYWwwWTATBgcqhkjOPQIBBggq
            hkjOPQMBBwNCAASEZVG7D77ZAGJb7Tif4XcRuPRm6B2EOfk8RAgiLIqb+WoN6J0b
            Ooo/p+p4TuX51Ha8AOx2h23pVxJ+RBaM9VvLo0IwQDAOBgNVHQ8BAf8EBAMCAqQw
            DwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUCfw3maNguTgbeJQcclVtHrACMrQw
            CgYIKoZIzj0EAwIDRwAwRAIgdyVvOidTdkFLdfvgJVuh8N6UC1gXLgGrSLKlL4hl
            NrsCIB+qaP8+1pfyUnmeLgiG8VwWCUMWe3gn/ZWUAZPRSUbk
            -----END CERTIFICATE-----
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: DAPR_CONTROLPLANE_NAMESPACE
          value: "dapr-system"
        - name: DAPR_CONTROLPLANE_TRUST_DOMAIN
          value: "cluster.local"
        - name: DAPR_SCHEDULER_HOST_ADDRESS
          value: "dapr-scheduler-server-0.dapr-scheduler-server.dapr-system.svc.cluster.local:50006,dapr-scheduler-server-1.dapr-scheduler-server.dapr-system.svc.cluster.local:50006,dapr-scheduler-server-2.dapr-scheduler-server.dapr-system.svc.cluster.local:50006"
        - name: DAPR_SCHEDULER_HOST_ADDRESS_DNS_A
          value: "dapr-scheduler-server-a.dapr-system.svc.cluster.local:443"
        readinessProbe:
          httpGet:
            path: /v1.0/healthz
            port: 3501
          initialDelaySeconds: 3
          periodSeconds: 6
          timeoutSeconds: 3
        livenessProbe:
          tcpSocket:
            port: 3501
          initialDelaySeconds: 3
          periodSeconds: 6
          timeoutSeconds: 3
      imagePullSecrets:
      - name: docker-registry-secret