kind: Service
apiVersion: v1
metadata:
  name: backendapi
  labels:
    app: myhellow
    service: backend
spec:
  selector:
    service: backend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 3500
      targetPort: 3500
      protocol: TCP
      name: dapr-http
    - port: 50001
      targetPort: 50001
      protocol: TCP
      name: dapr-grpc
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: myhellow
    service: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: backend
  template:
    metadata:
      labels:
        app: myhellow
        service: backend
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "backendapi"
        dapr.io/app-port: "80"
        dapr.io/enable-api-logging: "true"
        dapr.io/config: "tracing"
    spec:
      containers:
        - name: backendapi
          image: containerregistryre.azurecr.io/orderbackendimage:latest
        imagePullSecrets:
        - name: acr-auth-secret
          ports:
            - port: 80
              protocol: TCP
