apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderfrontendapp
  labels:
    app: orderfrontendapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderfrontendapp
  template:
    metadata:
      labels:
        app: orderfrontendapp
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "orderfrontendapp"
        dapr.io/app-port: "80"
        dapr.io/app-protocol: "http"
        dapr.io/metrics-enabled: "true"
    spec:
      containers:
      - name: orderfrontendapp
        image: reisenberg123/dapr-traffic-control-order-frontend:1.0
        ports:
        - containerPort: 80
        env:
        - name: APP_PORT
          value: "80"
        - name: DAPR_HTTP_PORT
          value: "3500"
        - name: DAPR_GRPC_PORT
          value: "50001"
        - name: APP_PROTOCOL
          value: "http"
        readinessProbe:
          httpGet:
            path: /health  # Adjust to app’s actual health endpoint
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /health  # Adjust to app’s actual health endpoint
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
      - name: daprd
        image: ghcr.io/dapr/daprd:1.15.4
        command: ["/daprd"]
        args:
        - "--app-id"
        - "orderfrontendapp"
        - "--app-port"
        - "80"
        - "--app-protocol"
        - "http"
        - "--dapr-http-port"
        - "3500"
        - "--dapr-grpc-port"
        - "50001"
        - "--metrics-port"
        - "9090"
        - "--log-level"
        - "info"
        readinessProbe:
          httpGet:
            path: /v1.0/healthz
            port: 3501
          initialDelaySeconds: 3
          periodSeconds: 6
          timeoutSeconds: 3
        livenessProbe:
          tcpSocket:
            port: 3501
          initialDelaySeconds: 3
          periodSeconds: 6
          timeoutSeconds: 3
      imagePullSecrets:
      - name: docker-registry-secret