apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderfrontendapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderfrontendapp
  template:
    metadata:
      labels:
        app: orderfrontendapp
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "orderfrontendapp"
        dapr.io/app-port: "3000"
    spec:
      containers:
      - name: orderfrontendapp
        image: {{ .Values.orderfrontendapp.image }}
        ports:
        - containerPort: 3000
      imagePullSecrets:
        - name: docker-registry-secret