apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-subscriber
  labels:
    app: python-subscriber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-subscriber
  template:
    metadata:
      labels:
        app: python-subscriber
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "python-subscriber"
        dapr.io/app-port: "5001"
        dapr.io/app-protocol: "http"
        dapr.io/metrics-enabled: "true"
    spec:
      containers:
      - name: python-subscriber
        image: reisenberg123/dapr-traffic-control-python-subscriber:1.0
        ports:
        - containerPort: 5001
        env:
        - name: DAPR_HTTP_PORT
          value: "3500"
        - name: DAPR_GRPC_PORT
          value: "50001"
        - name: APP_PROTOCOL
          value: "http"
        readinessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
      - name: daprd
        image: ghcr.io/dapr/daprd:1.15.4
        command: ["/daprd"]
        args:
        - "--dapr-http-port"
        - "3500"
        - "--dapr-grpc-port"
        - "50001"
        - "--dapr-internal-grpc-port"
        - "50002"
        - "--dapr-listen-addresses"
        - "[::1],127.0.0.1"
        - "--dapr-public-port"
        - "3501"
        - "--app-id"
        - "python-subscriber"
        - "--app-port"
        - "5001"
        - "--app-protocol"
        - "http"
        - "--log-level"
        - "debug"
        - "--dapr-graceful-shutdown-seconds"
        - "-1"
        - "--mode"
        - "kubernetes"
        - "--control-plane-address"
        - "dapr-api.dapr-system.svc.cluster.local:443"
        - "--enable-metrics"
        - "--metrics-port"
        - "9090"
        - "--placement-host-address"
        - "dapr-placement-server.dapr-system.svc.cluster.local:50005"
        env:
        - name: NAMESPACE
          value: "default"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: DAPR_CONTROLPLANE_NAMESPACE
          value: "dapr-system"
        readinessProbe:
          httpGet:
            path: /v1.0/healthz
            port: 3501
          initialDelaySeconds: 3
          periodSeconds: 6
          timeoutSeconds: 3
        livenessProbe:
          tcpSocket:
            port: 3501
          initialDelaySeconds: 3
          periodSeconds: 6
          timeoutSeconds: 3
      imagePullSecrets:
      - name: docker-registry-secret