apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-subscriber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-subscriber
  template:
    metadata:
      labels:
        app: python-subscriber
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "python-subscriber"
    spec:
      containers:
      - name: python-subscriber
        image: reisenberg123/dapr-traffic-control-python-subscriber:1.0
      imagePullSecrets:
        - name: docker-registry-secret