apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: sqldb
  namespace: default
spec:
  type: bindings.postgres
  version: v1
  metadata:
  - name: url # Required
    value: "user=postgres password=docker host=localhost port=5432 dbname=orders pool_min_conns=1 pool_max_conns=10"
  - name: direction
    value: "output"

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: postgresdata
  namespace: default
  labels:
    app: myhellow
    service: postgresdata
spec:
  replicas: 1
  selector:
    matchLabels:
      service: postgresdata
  template:
    metadata:
      labels:
        app: myhellow
        service: postgresdata
    spec:
      containers:
        - name: postgresdata
          image: bitnami/postgresql
          imagePullPolicy: IfNotPresent
          ports:
            - name: postgresserver
              containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: docker
            - name: POSTGRES_DB
              value: orders

---
kind: Service
apiVersion: v1
metadata:
  name: postgresdata
  namespace: default
  labels:
    app: myhellow
    service: postgresdata
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: tds
  selector:
    service: postgresdata
